### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by ThomasKoscheck** [DuckBoss/JJMumbleBot#101]
Hey,
I really like your project! For a better and quicker understanding of your projects and the installation process if would be really helpful to add some sample files (not a image) and improve the quickstart with more details and in depth examples.

**Comment by DuckBoss** [comment]
I'll look into this and work on it by the end of the week. Thank you!

**Comment by DuckBoss** [comment]
What kind of sample files were you thinking of by the way? I already include a sample config file and that's pretty much all you need to configure to start the bot. 
Any suggestions?

**Comment by ThomasKoscheck** [comment]
Maybe you could link to the sample files in the wiki. For myself, I found the sample files only after you mentioned them in the comment above.
I would also not include the image in the wiki (better you include the sample file there) as others cant copy strings/line out of the image, so the image is in my opinion a little bit useless at this location.

Also adding some sample commands/instructions in the **Quick start section** would improved the wiki largely.

The other pages are looking good for me :)

**Comment by DuckBoss** [comment]
I mention the sample config file in the quickstart but I guess it wasn't very clear. I'll correct this issue.
It's probably a good idea if I remove the image especially since the config is updated fairly often too.

Thanks for the help, I've been building the wiki as I release features and I've been in a rapid development phase. I will most likely rework the wiki and clean it up a lot.

**Comment by DuckBoss** [comment]
[JJMumbleBot v3.0.0 Pre-Release](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v3.0.0) will be getting completely reworked and easy-to-read documentation by the time I do a full release.
