### ISSUE TITLE
[Feature Request] pause and seek commands

### ISSUE THREAD

**Issue by Chili-Bebber** [DuckBoss/JJMumbleBot#169]
**Is your feature request related to a problem? Please describe.**
Apologies if this is a behavior already, but I could not seem to find it if it exists. I have found that I would really like to be able to pause and seek through the current track.

**Describe the solution you'd like**
I would like !pause and !resume commands as well as !seek \<seconds\> to make controlling the music easier.

**Comment by DuckBoss** [comment]
Hey there! I will continue working on this project after December 20th.
I'll see what I can do to incorporate this feature.

**Comment by DuckBoss** [comment]
Hey sorry for the long wait, I've been really busy.
I managed to get a !seek <seconds> command working, however due to the nature of how the mumble bot interfaces with mumble, I won't be able to add a !pause/!resume command.
I will be pushing the update for the !seek command soon.
Expect it to be in release v3.0.8 or later.
