### ISSUE TITLE
Error Certificate when start the project

### ISSUE THREAD

**Issue by tiagofagoncalves** [DuckBoss/JJMumbleBot#185]
**Describe the bug**
Error when start the project saying that "No such file or directory" in the certificate generation.

You can saw the error in this image: https://i.imgur.com/HibAIBB.png

I tried to put the field UserCertification empty and the bot start with no problem but then i put the commands and it doesn't make anything.

I put a print in "/usr/lib/python3.7/ssl.py" to saw whats happening and the in the certfile it puts the location of the UserCertification field but in keyfile it puts "None".

**Comment by DuckBoss** [comment]
What version of JJMumbleBot are you using?
Can you attach a screenshot of the certificate path in the config? 
(please don't show private connection information in your screenshot)

Also check these things:
- make sure the certificate is valid and you can use it to log into a server through the official mumble client. This is to make sure the certificate doesn't have any underlying issues.
- make sure the cert is a .pem file.
- make sure the path to the cert in the config file is a full system path.
- make sure the cert path in the config file doesn't contain any quotation marks.

**Comment by tiagofagoncalves** [comment]
I'm using version v2.3.1. 
Yes of course: https://i.imgur.com/MA57FZn.png

I tried use the bot without the certificate and it connects to the server and I can use the commands, but now the bot responds but when I choose the music it doesn't plays and after a few seconds it disconnects without any error message: https://i.imgur.com/W14EHIO.png

**Comment by DuckBoss** [comment]
I'm not sure what's causing problems in the certificate right now and I will have to look into it further at a later time. (I currently don't have an active linux development environment which is why the bot hasn't received major updates in the past few months)

The VLC problem where it doesn't play audio from youtube is usually a problem with youtube constantly changing their infrastructure and protecting from unauthorized video/audio extraction. 
This is resolved by making sure your youtube-dl python package is up to date and your 'youtube.lua' file is the most recently updated one from the VLC github link:
https://github.com/videolan/vlc/blob/master/share/lua/playlist/youtube.lua
If the problem still occurs, it usually means that the youtube-dl python package hasn't been updated to resolve the changes on youtube's side.

**Comment by DuckBoss** [comment]
Closed due to inactivity.
