### ISSUE TITLE
SoundBoard not playing audio files

### ISSUE THREAD

**Issue by DuckBoss** [DuckBoss/JJMumbleBot#193]
## THIS IS CREATED FOR: https://github.com/DuckBoss/JJMumbleBot/issues/186#issuecomment-616226583

I also don't get any sound when using a `.wav` file for the soundboard.

This is the audio file that I'm trying to use.
```
$ file rickroll.wav
rickroll.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 48000 Hz
```

JJMumbleBot will successfully list the file, but not play it.

`!sb 'rickroll'` according to the Wiki does not find the file `!sb rickroll` (without single quotes) does.

The log tells me
```
Message Received: [MacLemon -> !sb rickroll]
INFO:RuntimeLogging:Commands Received: [MacLemon -> !sb rickroll]
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
```
but there is no sound playing and my Mumble client also doesn't show any audio activity on the JJMumbleBot Icon in the list.

Am I doing this right? Should a `.wav` file with the specs mentioned above (converted via `ffmpeg`) play with JJMumbleBot? (It does play with VLC on macOS.) The server I'm running the bot on doesn't have a sound card obviously. :-)
If that file *should* actually play, then maybe there's a problem with `vlc` integration, rather than `youtube-dl`.

## Version info
- JJMumblebot is v2.3.1 (cloned via `git`)
- Python 3.7.7
- VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)

Anything else I can provide to help debugging this?

_Originally posted by @MacLemon in https://github.com/DuckBoss/JJMumbleBot/issues/186#issuecomment-616226583_

**Comment by DuckBoss** [comment]
There was a lot of information in that post so I'll post my thoughts as a short list:
1) The sound file specs seem to be fine. So I don't think it's an issue with the file.
2) Yes, the command needs to be used without single-quotes (the documentation does that so you can know where to type your file name)
3) The plugin doesn't have any issue integrating with **vlc** and it doesn't use the **youtube-dl** package at all so that shouldn't be the issue. I think there's a problem with your **vlc** installation or settings because it has worked on all the test-beds I've tried so far.

Additionally, you could try editing the **sound_board_helper.py** file in the plugins/sound_board folder
and removing the ```'--quiet' ``` parameter in the list as seen in line 76:
https://github.com/DuckBoss/JJMumbleBot/blob/32d6186326277f214bc3a8c7a995d165f49338dc/plugins/sound_board/sound_board_helper.py#L76 
This will allow vlc to display the error/log messages the next time you run the sound_board so it will be easier to identify what's causing the problem.

As of right now, I strongly believe it is some problem with VLC, but hopefully it's something trivial.

**Comment by or2b** [comment]
I had the same issue (?), removing then `'--quiet'` parameter as mentioned above helped me finding the problem in my setup.

In my case, I got the following output in my log file:

`VLC media player 3.0.10 Vetinari (revision 3.0.10-0-g7f145afa84)`
`[00005624ede9e2f0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused`
`[00005624edef3060] dbus interface error: Failed to connect to the D-Bus session daemon: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11`
`[00005624edef3060] main interface error: no suitable interface module`
`[00005624eddf8750] main libvlc error: interface "dbus,none" initialization failed`
`[00005624eddf8750] main libvlc error: D-Bus session bus connection failure: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11`
`[00005624edeeffe0] main interface error: no suitable interface module`
`[00005624eddf8750] main libvlc error: interface "globalhotkeys,none" initialization failed`
`[00005624edeeffe0] dummy interface: using the dummy interface module...`
`[00007f65480066e0] filesystem stream error: cannot open file //home/bot/bot1/botmedia/perm/sound_board/soundfile.wav (No such file or directory)`
`[00007f6544000c40] main input error: Your input can't be opened`
`[00007f6544000c40] main input error: VLC is unable to open the MRL 'file:////home/bot/bot1/botmedia/perm/sound_board/soundfile.wav'. Check the log for details.`
`[00007f65500017f0] idummy demux: command `quit'`

At first, I paid no attention to the errors that are saying, file not found. I tried to get rid of the dbus, X11 and pulseaudio errors... turns out, I can totally ignore these errors (they are still there but sound is playing).

However, the soundboard plugin does something odd, maybe I just have configured it incorrectly.

Example:

The `PermanentMediaDirectory` is configured to `/home/bot/bot1/botmedia/perm`. When the bot starts, it will create subfolders (i.e. `/home/bot/bot1/botmedia/perm/sound_board`)

However, the soundboard is only listing files from this path: `/home/bot/bot1/botmedia/permsound_board`

But it will only play them, when the files are in both folders.

In the end, the easy fix/workaround was to change the `PermanentMediaDirectory` to `/home/bot/bot1/botmedia/perm/` (trailing slash at the end). Then it will work as expected. 

So there is somewhere an issue with the path parsing, in my case `permsound_board` should actually be `perm/sound_board`.

**Comment by DuckBoss** [comment]
I'll review this soon, that does indeed sound like a path parsing problem. Unfortunately I won't be able to modify the code-base until next week. Will try to get this looked at soon.

**Comment by DuckBoss** [comment]
Fixed in version 2.3.2 release -> https://github.com/DuckBoss/JJMumbleBot/releases/tag/v2.3.2

**Comment by yquemener** [comment]
Maybe not a big deal, but I had a similar problem when using local path for PermanentMediaDirectory. I had put "media/" and it seemed to work fine, created the directories and downloading the youtube files in them but the playback failed. I changed it to an absolute path and it now works fine.

**Comment by DuckBoss** [comment]
Ah yes, all the directories/paths in the config.ini file are supposed to be absolute paths. Relative paths aren't supposed to work at all, but I think it worked initially because the python methods for directory creation and downloads in particular accept relative paths.
