### ISSUE TITLE
Some issues in the new ver

### ISSUE THREAD

**Issue by ajmandourah** [DuckBoss/JJMumbleBot#217]
Hello. Nice update .
some issues I find:

- in the config I think the TemporaryImageDirectory should be TemporaryMediaDirectory.
- the !help still doesnot work. 
- back in version 2 the youtube list wont work correctly. issues with youtube_dl dictionary keys. and the issue continued to ver 3.0.5

Thanks for your awesome work man .

**Comment by DuckBoss** [comment]
Hey thanks a lot for listing out some issues for me.
I'll address them soon and update this thread as I make progress.
Could you clarify some things for me please?
- Does the !help command work after deleting the internal jjmumblebot.db database file and letting the bot regenerate it?
- What youtube list are you referring to? The queue has been working on my end across multiple computers if that's what you're referring to. I need little bit more information about this.

**Comment by ajmandourah** [comment]
I see so there is no !help only now and instead there is a help only for every plugin? I kinda liked the standalone help which can direct to to other sections like the old v2. Make it easier for other users who is not into programming.

I meant a YouTube Playlist. Try putting a YouTube Playlist in !link and it downloads the thumbnail but it get a keyerror. I didn't take a look at the whole code but I guess it consider the whole Playlist as a one video and thus YouTube-dl can't figure up the information dictionary. Probably iterating through the whole list will get it fixed. Or adding every video in the Playlist in the play queue.

Will be checking today and let you know if something comes up

**Comment by DuckBoss** [comment]
Ah I understand now.

- I will make some changes so that the regular !help command does something, maybe list out the available plugins and tells you how to check the help commands for each plugin.
Version 2 had a similar design where you had to do !help_youtube or !help_sound_board.

- As far as the !link command, it is only supposed to be used for single videos. You should be using the !playlist command for playlists. I will add an error message to the !link command if users try to enter playlists to prevent this confusion later.

**Comment by DuckBoss** [comment]
Please check [v3.0.7 Release](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v3.0.7) to see if it fixes all the problems you've encountered.
<br>The release notes explain all the changes I made. Most of them are concerning the problems you encountered.
